### ISSUE TITLE
不正な店情報が交じると世界地図が表示される

### ISSUE THREAD

**Issue by atachibana** [iemeshi/app#5]
店名がないなど、CSV ファイルに1件でも不正な店情報が交じると
`Input data given to 'shops' is not a valid GeoJSON object."`
が発生し、すべての情報の読み取りが捨てられ、世界地図が表示されます。

リリース後に店情報を追加していると、このエラーにぶつかります。

回避コードは以下です (間抜けなリポジトリを作ってしまい、こちらにプルリクエストを送れない...)
https://github.com/atachibana/iemeshi/pull/2/files

理想的には出力時に例外を補足すべきでしょうがコードが難しくて分からず...。

**Comment by miya0001** [comment]
あざっす！
